services:
  - type: web
    name: p2p-energy-flat
    env: python
    buildCommand: pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
